### ISSUE TITLE
I like to add nameservers for my subdomain and want to chnage cname to ns

### ISSUE THREAD

**Issue by ALBINPRAVEEN** [DennisKidman/io.day#31]

**Comment by DennisKidman** [comment]
Sure what is the domain and NS value?

**Comment by ALBINPRAVEEN** [comment]
can u say any alternative of cloudflare dns .I was using cloudflare for my domains but this is a subdomain.so it wont support cloudflare any alternative @DennisKidman

**Comment by ALBINPRAVEEN** [comment]
can u help me out

**Comment by DennisKidman** [comment]
Hello you can try this @ALBINPRAVEEN 
https://1984.hosting/product/freedns/

**Comment by ALBINPRAVEEN** [comment]
ns0.1984.is.

**Comment by ALBINPRAVEEN** [comment]
ns0.1984.is.

ns1.1984hosting.com.

ns1.1984.is.

ns2.1984hosting.com.

ns2.1984.is. 


ttl is  86400

**Comment by ALBINPRAVEEN** [comment]
can u add this bro

**Comment by ALBINPRAVEEN** [comment]
thanks btw bro for the suggestion..1984 only support one free dns hosting and is there anything similar to cloudflare u know

**Comment by DennisKidman** [comment]
Yeah, but Cloudflare is also a free DNS service? Do you want SSL with DNS?

**Comment by DennisKidman** [comment]
> ns0.1984.is.
> 
> ns1.1984hosting.com.
> 
> ns1.1984.is.
> 
> ns2.1984hosting.com.
> 
> ns2.1984.is.
> 
> ttl is 86400

So you want me to add this?

**Comment by ALBINPRAVEEN** [comment]
Ys

**Comment by DennisKidman** [comment]
Added ; https://www.whatsmydns.net/#NS/albinpraveen.io.day

**Comment by DennisKidman** [comment]
May I know the purpose of your using the NS record? Did you use the CNAME or A? By default io.day domains need to use HTTPS to connect, so if you have HTTP your website might not be accessible

**Comment by ALBINPRAVEEN** [comment]
Ys bro I deployed on vercel and it it https and added the cname on 1984 but does not work

**Comment by DennisKidman** [comment]
For vercel you don't need to add NS... You can use the old CNAME

**Comment by ALBINPRAVEEN** [comment]
ok bro its all right sry for the mistake bro pls dd txt for me...

**Comment by ALBINPRAVEEN** [comment]
![image](https://user-images.githubusercontent.com/68139513/225620997-a57972ab-c7d8-4165-aca0-f4bb6fb05ba7.png)
can u add this txt bro

**Comment by ALBINPRAVEEN** [comment]
vc-domain-verify=albinpraveen.io.day,87b46e12382915f9821a

this is the txt

**Comment by ALBINPRAVEEN** [comment]
Can u add the txt bro cname not working

**Comment by DennisKidman** [comment]
I have added the record pls check
https://www.whatsmydns.net/#TXT/albinpraveen.io.day

**Comment by ALBINPRAVEEN** [comment]
``vc-domain-verify=albinpraveen.io.day,87b46e12382915f9821a


Is this the value u added in txt


Vercel is not showing not configured

**Comment by DennisKidman** [comment]
yes, thats the value... I think this is more of Vercel problem than our end problem. Also, I think this messed up because you keep changing the records

**Comment by DennisKidman** [comment]
https://www.whatsmydns.net/#TXT/albinpraveen.io.day

Please check here. please!

**Comment by DennisKidman** [comment]
does it have spacing problem? Please double check

**Comment by DennisKidman** [comment]
Also @ALBINPRAVEEN , you only give me TXT record there is no CNAME record

**Comment by ALBINPRAVEEN** [comment]
![Screenshot_2023-03-17_13-33-42](https://user-images.githubusercontent.com/68139513/225847404-d7befa7f-ecea-441e-a43a-95f3e09c3a07.png)
This is the txt bro and it is correct idk what happenef

**Comment by ALBINPRAVEEN** [comment]
vc-domain-verify=albinpraveen.io.day,87b46e12382915f9821a


This is the txt that I copied from vercel

**Comment by DennisKidman** [comment]
https://www.whatsmydns.net/#TXT/_vercel.io.day

I have added the record. Try to refresh it on the config page

**Comment by ALBINPRAVEEN** [comment]
Thnkz bro it worked perfect

**Comment by DennisKidman** [comment]
No sweat, Happy it worked!
