### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by adolphin-CEO** [DennisKidman/io.day#45]
This subdomain is long-term maintenance?

**Comment by adolphin-CEO** [comment]
Your domain is amazing,& can I apply for an NS record?

**Comment by DennisKidman** [comment]
Hi, yes, this domain is intended for long-term use. Keep in mind that the .day domain is on the HSTS preload list by default, so if you don't have an SSL cert, some users might not be able to reach your site. No worries though, I've also got lag.tf and xyz.wf domain names as alternatives if you'd rather not deal with the HSTS stuff.

**Comment by adolphin-CEO** [comment]
Glad to receive your reply,Which repositories of xyz.wf?I can't find it.

**Comment by adolphin-CEO** [comment]
& Can I append the NS records of xyz.wf&io.day at the same time?

**Comment by DennisKidman** [comment]
Currently, there is no repository for xyz.wf as I am working on a new and faster way to register domain names for lag.tf and xyz.wf. However, if you add the NS record to the current repository, I can include it in the xyz.wf records. @adolphin-CEO
