### ISSUE TITLE
Building a Landing page for this project would feel great !

### ISSUE THREAD

**Issue by HarisETH** [DennisKidman/io.day#7]
If you are open to build a landing page for this project , I'd be interested to contribute. It would be helpful to devs who want to use the domain . What's your thought on this ?

**Comment by DennisKidman** [comment]
Hey, that's a fantastic idea! I'm actually planning to build a similar website myself, something like the one over at https://register.is-a.dev/. This kind of setup allows users to quickly and easily acquire a domain without any hassle. 

If you'd like to contribute further, I'd be more than happy to chat with you on Discord. Here's the link to the server: https://discord.gg/DebYuWBC.

**Comment by DennisKidman** [comment]
I've added this to the TODO list

**Comment by WilliamDavidHarrison** [comment]
@DennisKidman Maintainer of is-a.dev here, `register.is-a.dev`'s code is open source and can be found [here](https://github.com/is-a-dev/register.is-a.dev). Let me know if it helps!

**Comment by DennisKidman** [comment]
Hey, @WilliamDavidHarrison thanks for the heads up on the code for register.is-a.dev. I'll definitely check it out and see if it can be helpful for my project!

**Comment by WilliamDavidHarrison** [comment]
No problem

**Comment by broduer40** [comment]
I'll gladly help where I can, If I see something I could improve for the project I'll be sure to create a PR :) Great job!

**Comment by DennisKidman** [comment]
Hey check out our new website! @WilliamDavidHarrison @broduer40 @HarisETH
